name: PyTests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    name: Run pytest (Python ${{ matrix.python-version }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12", "3.13"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      # If you use Poetry, this block installs with Poetry; otherwise it falls back to pip.
      - name: Install dependencies (Poetry)
        if: hashFiles('poetry.lock') != ''
        run: |
          pip install poetry
          poetry config virtualenvs.create false
          poetry install --no-interaction --no-root
      - name: Install dependencies (pip)
        if: hashFiles('poetry.lock') == ''
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          # Optional extras commonly used in tests:
          pip install pytest pytest-cov

      - name: Run pytest
        run: |
          pytest -q --maxfail=1 --disable-warnings \
                 --cov=airalo --cov-report=xml --cov-report=term \
                 tests

      - name: Upload coverage artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.python-version }}
          path: coverage.xml
